### ISSUE TITLE
[BUG] Multiplication overflow during noise creation

### ISSUE THREAD

**Issue by AustinHellerRepo** [gp-97/perlin2d#4]
When setting up the PerlinNoise2D with the configuration below it panics.
```
let perlin = PerlinNoise2D::new(6, 1.0, 1.0, 1.0, 2.0, (1.0, 1.0), 0.5, -2074058151);
let noise = perlin.get_noise(0.0, 0.0);
```

Error:
```
thread 'main' panicked at /home/austin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perlin2d-0.2.6/src/lib.rs:164:54:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_const::panic_const_mul_overflow
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:180:21
   3: perlin2d::PerlinNoise2D::noise
             at /home/austin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perlin2d-0.2.6/src/lib.rs:164:54
   4: perlin2d::PerlinNoise2D::get_value
             at /home/austin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perlin2d-0.2.6/src/lib.rs:176:24
   5: perlin2d::PerlinNoise2D::total
             at /home/austin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perlin2d-0.2.6/src/lib.rs:144:18
   6: perlin2d::PerlinNoise2D::get_noise
             at /home/austin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perlin2d-0.2.6/src/lib.rs:135:38
   7: perlin::main
             at ./examples/perlin.rs:482:25
   8: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
```

Looking at the source code at line 165, I see that there exists the following code:
```
let t = Wrapping(n) * Wrapping(n) * Wrapping(n * 15731 + 789221) + Wrapping(1376312589);
```
The `n * 15731` is the spot where I believe this bug occurs.

**Desktop and OS names and versions:**
Ubuntu 22.04.4
perlin2d v0.2.6

**Comment by manen** [comment]
same thing happening on debian 12, perlin2d 0.2.6

early on i could make it work by adjusting the seed (sometimes) but now it always crashes
